apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: collab
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}




