/**
 * Document images data module — metadata for images embedded in documents.
 *
 * Rows map an image id to its owning document and S3 object. Bytes live in S3
 * (see server/s3-images.js); this table is the source of truth for permission
 * scoping (image belongs to a doc) and cleanup.
 */

// Database pool - set by init function
let pool = null;

/**
 * Initialize the module with a database pool
 * @param {Pool} dbPool - PostgreSQL connection pool
 */
function init(dbPool) {
  pool = dbPool;
}

/**
 * Create an image metadata row
 * @param {object} args
 * @param {string} args.id - Image UUID (generated by the caller so the S3 key can embed it)
 * @param {string} args.docId - Owning document UUID
 * @param {string|null} args.uploaderId - Uploading user UUID
 * @param {string} args.mimeType - Image MIME type
 * @param {string|null} args.filename - Original filename
 * @param {number} args.byteSize - Decoded byte size
 * @param {string} args.s3Key - S3 object key
 * @returns {Promise<{id: string}>}
 */
async function createImage({ id, docId, uploaderId, mimeType, filename, byteSize, s3Key }) {
  if (!pool) throw new Error('Document images module not initialized');

  const result = await pool.query(
    `INSERT INTO document_images (id, doc_id, uploader_id, mime_type, filename, byte_size, s3_key)
     VALUES ($1, $2, $3, $4, $5, $6, $7)
     RETURNING id`,
    [id, docId, uploaderId, mimeType, filename, byteSize, s3Key]
  );

  return result.rows[0];
}

/**
 * Get an image row by id, scoped to its document.
 * Querying by both ids prevents serving an image under a doc the user can't see.
 * @param {string} imageId - Image UUID
 * @param {string} docId - Document UUID
 * @returns {Promise<object|null>}
 */
async function getImage(imageId, docId) {
  if (!pool) throw new Error('Document images module not initialized');

  const result = await pool.query(
    'SELECT * FROM document_images WHERE id = $1 AND doc_id = $2',
    [imageId, docId]
  );

  return result.rows[0] || null;
}

/**
 * List S3 keys for all images belonging to a document (used for cleanup).
 * @param {string} docId - Document UUID
 * @returns {Promise<string[]>}
 */
async function listKeysForDoc(docId) {
  if (!pool) throw new Error('Document images module not initialized');

  const result = await pool.query(
    'SELECT s3_key FROM document_images WHERE doc_id = $1',
    [docId]
  );

  return result.rows.map((r) => r.s3_key);
}

module.exports = {
  init,
  createImage,
  getImage,
  listKeysForDoc,
};
