#!/usr/bin/env bash
# cmd_config.sh — print the resolved configuration. For debugging.

main() {
  cat <<EOF
config file: $COLLAB_DC_CONFIG_FILE
schema_version: $COLLAB_DC_SCHEMA_VERSION

COLLAB_DC_TOOL_DIR=$COLLAB_DC_TOOL_DIR
COLLAB_DC_TARGET_REPO=$COLLAB_DC_TARGET_REPO
COLLAB_DC_TARGET_NAME=$COLLAB_DC_TARGET_NAME
COLLAB_DC_WORKSPACE_MOUNT=$COLLAB_DC_WORKSPACE_MOUNT
COLLAB_DC_CONTEXT=$COLLAB_DC_CONTEXT
COLLAB_DC_NAMESPACE=$COLLAB_DC_NAMESPACE
COLLAB_DC_DEPLOYMENT=$COLLAB_DC_DEPLOYMENT
COLLAB_DC_PG_SERVICE=$COLLAB_DC_PG_SERVICE
COLLAB_DC_PG_PORT=$COLLAB_DC_PG_PORT
COLLAB_DC_REDIS_SERVICE=$COLLAB_DC_REDIS_SERVICE
COLLAB_DC_REDIS_PORT=$COLLAB_DC_REDIS_PORT
COLLAB_DC_IMAGE=$COLLAB_DC_IMAGE
COLLAB_DC_MUTAGEN_SYNC=$COLLAB_DC_MUTAGEN_SYNC
COLLAB_DC_MOUNT_PATHS=$COLLAB_DC_MOUNT_PATHS
COLLAB_DC_MOUNT_RW_PATHS=$COLLAB_DC_MOUNT_RW_PATHS
COLLAB_DC_CLAUDE_SESSION_DIR=$COLLAB_DC_CLAUDE_SESSION_DIR
resolved mount paths (rw = writable from the pod):
$(resolved_mount_paths | while IFS= read -r p; do
    [[ -z "$p" ]] && continue
    if path_is_rw "$p"; then printf '  %s  [rw]\n' "$p"; else printf '  %s  [ro]\n' "$p"; fi
  done)
EOF
}
